### ISSUE TITLE
Style support appears to be spotty

### ISSUE THREAD

**Issue by Shizen** [rstacruz/kingraph#7]
I'm not really terribly familiar with graphviz, practically speaking, but even in your own examples, the `penstyle: dashed` doesn't do anything (from the Potterverse example). (is that even a valid setting)?  Anyway, I tried a few others, `shape: hexagon`, `style: dashed`, `dir: both` etc.  all were ignored.  I didn't look at the source to see *why*, however.

**Comment by rstacruz** [comment]
Sorry, I don't know enough to answer this admittedly :(

**Comment by rstacruz** [comment]
Btw, those get applied as graphviz attributes: http://graphviz.org/doc/info/attrs.html

so the penstyle: dashed would've been made into:

```
abc -> def [penstyle=dashed]
```

looking at the docs, yeah, i'm not sure penstyle was valid in the first place.
